version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./custom_conf/jellyfin/config:/config
      - ./custom_conf/jellyfin/cache:/cache
      - type: bind
        source: ./media
        target: /media
    env_file:
      - global.env